# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /sbin/cmake

# The command to remove a file.
RM = /sbin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nsomnia/Documents/projectm_audio_visualizer_qt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nsomnia/Documents/projectm_audio_visualizer_qt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/sbin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/sbin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/sbin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nsomnia/Documents/projectm_audio_visualizer_qt/CMakeFiles /home/nsomnia/Documents/projectm_audio_visualizer_qt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nsomnia/Documents/projectm_audio_visualizer_qt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AuroraVisualizer

# Build rule for target.
AuroraVisualizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AuroraVisualizer
.PHONY : AuroraVisualizer

# fast build rule for target.
AuroraVisualizer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/build
.PHONY : AuroraVisualizer/fast

#=============================================================================
# Target rules for targets named AuroraVisualizer_autogen_timestamp_deps

# Build rule for target.
AuroraVisualizer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AuroraVisualizer_autogen_timestamp_deps
.PHONY : AuroraVisualizer_autogen_timestamp_deps

# fast build rule for target.
AuroraVisualizer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer_autogen_timestamp_deps.dir/build.make CMakeFiles/AuroraVisualizer_autogen_timestamp_deps.dir/build
.PHONY : AuroraVisualizer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named AuroraVisualizer_autogen

# Build rule for target.
AuroraVisualizer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AuroraVisualizer_autogen
.PHONY : AuroraVisualizer_autogen

# fast build rule for target.
AuroraVisualizer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer_autogen.dir/build.make CMakeFiles/AuroraVisualizer_autogen.dir/build
.PHONY : AuroraVisualizer_autogen/fast

#=============================================================================
# Target rules for targets named AuroraTests

# Build rule for target.
AuroraTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AuroraTests
.PHONY : AuroraTests

# fast build rule for target.
AuroraTests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/AuroraTests.dir/build.make tests/CMakeFiles/AuroraTests.dir/build
.PHONY : AuroraTests/fast

#=============================================================================
# Target rules for targets named AuroraTests_autogen_timestamp_deps

# Build rule for target.
AuroraTests_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AuroraTests_autogen_timestamp_deps
.PHONY : AuroraTests_autogen_timestamp_deps

# fast build rule for target.
AuroraTests_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/AuroraTests_autogen_timestamp_deps.dir/build.make tests/CMakeFiles/AuroraTests_autogen_timestamp_deps.dir/build
.PHONY : AuroraTests_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named AuroraTests_autogen

# Build rule for target.
AuroraTests_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AuroraTests_autogen
.PHONY : AuroraTests_autogen

# fast build rule for target.
AuroraTests_autogen/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/AuroraTests_autogen.dir/build.make tests/CMakeFiles/AuroraTests_autogen.dir/build
.PHONY : AuroraTests_autogen/fast

AuroraVisualizer_autogen/mocs_compilation.o: AuroraVisualizer_autogen/mocs_compilation.cpp.o
.PHONY : AuroraVisualizer_autogen/mocs_compilation.o

# target to build an object file
AuroraVisualizer_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/AuroraVisualizer_autogen/mocs_compilation.cpp.o
.PHONY : AuroraVisualizer_autogen/mocs_compilation.cpp.o

AuroraVisualizer_autogen/mocs_compilation.i: AuroraVisualizer_autogen/mocs_compilation.cpp.i
.PHONY : AuroraVisualizer_autogen/mocs_compilation.i

# target to preprocess a source file
AuroraVisualizer_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/AuroraVisualizer_autogen/mocs_compilation.cpp.i
.PHONY : AuroraVisualizer_autogen/mocs_compilation.cpp.i

AuroraVisualizer_autogen/mocs_compilation.s: AuroraVisualizer_autogen/mocs_compilation.cpp.s
.PHONY : AuroraVisualizer_autogen/mocs_compilation.s

# target to generate assembly for a file
AuroraVisualizer_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/AuroraVisualizer_autogen/mocs_compilation.cpp.s
.PHONY : AuroraVisualizer_autogen/mocs_compilation.cpp.s

src/core/LogCatcher.o: src/core/LogCatcher.cpp.o
.PHONY : src/core/LogCatcher.o

# target to build an object file
src/core/LogCatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/core/LogCatcher.cpp.o
.PHONY : src/core/LogCatcher.cpp.o

src/core/LogCatcher.i: src/core/LogCatcher.cpp.i
.PHONY : src/core/LogCatcher.i

# target to preprocess a source file
src/core/LogCatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/core/LogCatcher.cpp.i
.PHONY : src/core/LogCatcher.cpp.i

src/core/LogCatcher.s: src/core/LogCatcher.cpp.s
.PHONY : src/core/LogCatcher.s

# target to generate assembly for a file
src/core/LogCatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/core/LogCatcher.cpp.s
.PHONY : src/core/LogCatcher.cpp.s

src/core/audio/AudioEngine.o: src/core/audio/AudioEngine.cpp.o
.PHONY : src/core/audio/AudioEngine.o

# target to build an object file
src/core/audio/AudioEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/core/audio/AudioEngine.cpp.o
.PHONY : src/core/audio/AudioEngine.cpp.o

src/core/audio/AudioEngine.i: src/core/audio/AudioEngine.cpp.i
.PHONY : src/core/audio/AudioEngine.i

# target to preprocess a source file
src/core/audio/AudioEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/core/audio/AudioEngine.cpp.i
.PHONY : src/core/audio/AudioEngine.cpp.i

src/core/audio/AudioEngine.s: src/core/audio/AudioEngine.cpp.s
.PHONY : src/core/audio/AudioEngine.s

# target to generate assembly for a file
src/core/audio/AudioEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/core/audio/AudioEngine.cpp.s
.PHONY : src/core/audio/AudioEngine.cpp.s

src/gui/MainWindow.o: src/gui/MainWindow.cpp.o
.PHONY : src/gui/MainWindow.o

# target to build an object file
src/gui/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/MainWindow.cpp.o
.PHONY : src/gui/MainWindow.cpp.o

src/gui/MainWindow.i: src/gui/MainWindow.cpp.i
.PHONY : src/gui/MainWindow.i

# target to preprocess a source file
src/gui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/MainWindow.cpp.i
.PHONY : src/gui/MainWindow.cpp.i

src/gui/MainWindow.s: src/gui/MainWindow.cpp.s
.PHONY : src/gui/MainWindow.s

# target to generate assembly for a file
src/gui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/MainWindow.cpp.s
.PHONY : src/gui/MainWindow.cpp.s

src/gui/Renderer.o: src/gui/Renderer.cpp.o
.PHONY : src/gui/Renderer.o

# target to build an object file
src/gui/Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/Renderer.cpp.o
.PHONY : src/gui/Renderer.cpp.o

src/gui/Renderer.i: src/gui/Renderer.cpp.i
.PHONY : src/gui/Renderer.i

# target to preprocess a source file
src/gui/Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/Renderer.cpp.i
.PHONY : src/gui/Renderer.cpp.i

src/gui/Renderer.s: src/gui/Renderer.cpp.s
.PHONY : src/gui/Renderer.s

# target to generate assembly for a file
src/gui/Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/Renderer.cpp.s
.PHONY : src/gui/Renderer.cpp.s

src/gui/SongTitleAnimator.o: src/gui/SongTitleAnimator.cpp.o
.PHONY : src/gui/SongTitleAnimator.o

# target to build an object file
src/gui/SongTitleAnimator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/SongTitleAnimator.cpp.o
.PHONY : src/gui/SongTitleAnimator.cpp.o

src/gui/SongTitleAnimator.i: src/gui/SongTitleAnimator.cpp.i
.PHONY : src/gui/SongTitleAnimator.i

# target to preprocess a source file
src/gui/SongTitleAnimator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/SongTitleAnimator.cpp.i
.PHONY : src/gui/SongTitleAnimator.cpp.i

src/gui/SongTitleAnimator.s: src/gui/SongTitleAnimator.cpp.s
.PHONY : src/gui/SongTitleAnimator.s

# target to generate assembly for a file
src/gui/SongTitleAnimator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/SongTitleAnimator.cpp.s
.PHONY : src/gui/SongTitleAnimator.cpp.s

src/gui/TextRenderer.o: src/gui/TextRenderer.cpp.o
.PHONY : src/gui/TextRenderer.o

# target to build an object file
src/gui/TextRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/TextRenderer.cpp.o
.PHONY : src/gui/TextRenderer.cpp.o

src/gui/TextRenderer.i: src/gui/TextRenderer.cpp.i
.PHONY : src/gui/TextRenderer.i

# target to preprocess a source file
src/gui/TextRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/TextRenderer.cpp.i
.PHONY : src/gui/TextRenderer.cpp.i

src/gui/TextRenderer.s: src/gui/TextRenderer.cpp.s
.PHONY : src/gui/TextRenderer.s

# target to generate assembly for a file
src/gui/TextRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/gui/TextRenderer.cpp.s
.PHONY : src/gui/TextRenderer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AuroraVisualizer.dir/build.make CMakeFiles/AuroraVisualizer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... AuroraTests_autogen"
	@echo "... AuroraTests_autogen_timestamp_deps"
	@echo "... AuroraVisualizer_autogen"
	@echo "... AuroraVisualizer_autogen_timestamp_deps"
	@echo "... AuroraTests"
	@echo "... AuroraVisualizer"
	@echo "... AuroraVisualizer_autogen/mocs_compilation.o"
	@echo "... AuroraVisualizer_autogen/mocs_compilation.i"
	@echo "... AuroraVisualizer_autogen/mocs_compilation.s"
	@echo "... src/core/LogCatcher.o"
	@echo "... src/core/LogCatcher.i"
	@echo "... src/core/LogCatcher.s"
	@echo "... src/core/audio/AudioEngine.o"
	@echo "... src/core/audio/AudioEngine.i"
	@echo "... src/core/audio/AudioEngine.s"
	@echo "... src/gui/MainWindow.o"
	@echo "... src/gui/MainWindow.i"
	@echo "... src/gui/MainWindow.s"
	@echo "... src/gui/Renderer.o"
	@echo "... src/gui/Renderer.i"
	@echo "... src/gui/Renderer.s"
	@echo "... src/gui/SongTitleAnimator.o"
	@echo "... src/gui/SongTitleAnimator.i"
	@echo "... src/gui/SongTitleAnimator.s"
	@echo "... src/gui/TextRenderer.o"
	@echo "... src/gui/TextRenderer.i"
	@echo "... src/gui/TextRenderer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

